# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/Teaching/NUS/TA/CG3207/Lab/__S1_AY2016-17/Work/Lab1/simple_count_Verilog/simple_count_Verilog.cache/wt [current_project]
set_property parent.project_path F:/Teaching/NUS/TA/CG3207/Lab/__S1_AY2016-17/Work/Lab1/simple_count_Verilog/simple_count_Verilog.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib F:/Teaching/NUS/TA/CG3207/Lab/__S1_AY2016-17/Work/Lab1/simple_count_Verilog/simple_count_Verilog.srcs/sources_1/new/simple_count.v
read_xdc F:/Teaching/NUS/TA/CG3207/Lab/__S1_AY2016-17/Work/Lab1/simple_count_Verilog/simple_count_Verilog.srcs/constrs_1/imports/Desktop/Nexys4_Master.xdc
set_property used_in_implementation false [get_files F:/Teaching/NUS/TA/CG3207/Lab/__S1_AY2016-17/Work/Lab1/simple_count_Verilog/simple_count_Verilog.srcs/constrs_1/imports/Desktop/Nexys4_Master.xdc]

synth_design -top simple_count -part xc7a100tcsg324-1
write_checkpoint -noxdef simple_count.dcp
catch { report_utilization -file simple_count_utilization_synth.rpt -pb simple_count_utilization_synth.pb }
